Created Dockerfile for Docker Image
Would-You-Bot/website pull request #41
Opened 2023-10-02 12:36 UTC by GopalVerma1303

Hey!

- [x] Create Docker image using Dockerfile
- [ ] Deploy Docker image to VPS/VDS for automatic deployment

### Steps to create Docker image

1. [Install Docker](https://docs.docker.com/get-docker/) on your machine.
1. Build your container: `docker build -t would-you-bot-website .`.
1. Run your container: `docker run -p 3000:3000 would-you-bot-website`.

You can view your images created with `docker images`.

Please review and provide any feedback. Thank you!

2023-10-02 13:24 UTC, mezotv requested changes
Could you remove the package-lock file and get rid of anything that isnt part of the focker integration?

2023-10-02 13:38 UTC, GopalVerma1303 commented
Sure

2023-10-02 14:57 UTC, mezotv commented
I noticed you have the vps/vds workflow unchecked is this something you are wanting to add to this aswell?

2023-10-02 16:09 UTC, GopalVerma1303 commented
> I noticed you have the vps/vds workflow unchecked is this something you are wanting to add to this aswell?

Absolutely, I'd love to incorporate the VPS/VDS workflow. Could we create a new issue to handle this separately and keep our current focus intact? Thanks!

2023-10-02 16:13 UTC, mezotv commented
> > I noticed you have the vps/vds workflow unchecked is this something you are wanting to add to this aswell?
> 
> Absolutely, I'd love to incorporate the VPS/VDS workflow. Could we create a new issue to handle this separately and keep our current focus intact? Thanks!
> 

Sure just create an issue and I will assign it to you!

2023-10-02 16:26 UTC, GopalVerma1303 commented
I accidentally closed the merge request. Could you please re-review and merge it into the main branch? Thanks!

2023-10-02 16:34 UTC, mezotv commented
> I accidentally closed the merge request. Could you please re-review and merge it into the main branch? Thanks!

Let me test it together with the auto deploy workflow then I will!

2023-10-02 19:11 UTC, GopalVerma1303 commented
Could you please specify the hosting provider and share instructions on how to obtain the required credentials for the deployment? Thanks!

2023-10-02 19:58 UTC, mezotv commented
For the workflow this might be a good Inspiration https://github.com/EddieHubCommunity/BioDrop/blob/main/.github/workflows/publish-ghcr.yml

2023-10-03 09:44 UTC, mezotv commented
> Hey! I've created Issue #46 but didn't have permission to add labels. Could you please add the "hacktoberfest" label? Thanks!

Alright there you go!

2023-10-03 09:47 UTC, mezotv requested changes
In the code I saw port 3000 being used a lot is it possible to switch that since our production server uses port 2123 for the website.

2023-10-03 09:47 UTC, mezotv commented on Dockerfile
> +CMD ["node", "server.js"]
What is that supposed to do? Server.js isn't a file we have.

2023-10-03 10:50 UTC, GopalVerma1303 commented on Dockerfile
> +CMD ["node", "server.js"]
The server.js file in `.next/standalone/server.js` in Next.js is a minimal server that can be used to start your Next.js application in production. It is generated when you build your application with the `output: standalone` option in your next.config.js file.

2023-10-03 10:52 UTC, GopalVerma1303 commented
You can use this command run your container: `docker run -p 2123:2123 would-you-bot-website`

2023-10-03 12:23 UTC, mezotv commented
> You can use this command to run your container: `docker run -p 2123:2123 would-you-bot-website`

Could you revert the changes you have done to the sitemap?

2023-10-03 12:26 UTC, mezotv requested changes

2023-10-03 12:26 UTC, mezotv commented on Dockerfile
> +CMD ["node", "server.js"]
Id much rather not have this there as well as the standalone extension. Could you get rid of those?

2023-10-03 12:26 UTC, mezotv commented on next.config.js
> +  output: 'standalone',
Remove this please!

2023-10-03 12:26 UTC, mezotv commented on public/sitemap-0.xml
>  </urlset>
Revert the changes here!

2023-10-03 12:26 UTC, mezotv commented on README.md
Revert those changes please!

2023-10-03 14:15 UTC, GopalVerma1303 commented on README.md
Sure

2023-10-03 14:16 UTC, GopalVerma1303 commented on next.config.js
> +  output: 'standalone',
Sure

2023-10-03 16:45 UTC, GopalVerma1303 commented on Dockerfile
> +CMD ["node", "server.js"]
I have made some updates. Kindly review : [e78340f](https://github.com/Would-You-Bot/website/pull/41/commits/e78340f08c9b5e39663de7230647a70eb9533ea2)

2023-10-03 16:55 UTC, mezotv commented
Will be checking this later thank you!

2023-10-03 17:07 UTC, mezotv commented
Alright, I checked it and it seems to work well, tho I have a question how would the github workflow for this work?

2023-10-04 01:38 UTC, mezotv commented
- Get rid of the redundant if statements for different lockfile types (npm, yarn, pnpm) since only one lockfile should be pushed to GitHub.

- Ensure that the code installs the necessary package manager (pnpm) before installing dependencies or building the app to avoid dependency conflicts.

- Consider changing file permissions after the build process to enhance security.

- Explicitly expose the port used by the application to ensure proper networking.

2023-10-06 18:49 UTC, mezotv commented
Hey @GopalVerma1303, will the workflow be added to this pr as well?

2023-10-06 18:54 UTC, GopalVerma1303 commented
> Hey @GopalVerma1303, will the workflow be added to this pr as well?

Hey! I am planning to creating a new pr for this(Issue: #46) so as to keep our current focus intact.

2023-10-06 18:58 UTC, mezotv commented
> > Hey @GopalVerma1303, will the workflow be added to this pr as well?
> 
> Hey! I am planning to creating a new pr for this(Issue: #46) so as to keep our current focus intact.

Hmm sounds good give me around an hour and I will test this!

2023-10-06 20:19 UTC, mezotv approved these changes
I got a bit confused with the whole server setup but I pushed it to the server and it's working well. Thanks for this pull request!

2023-10-07 03:21 UTC, Podskio approved these changes

2023-10-07 03:21 UTC, merged