Created Contributing.md file
Would-You-Bot/website pull request #55
Opened 2023-10-02 20:37 UTC by pbelokon

This PR is for issue https://github.com/Would-You-Bot/website/issues/48.

The PR adds Contributing.md file with contribution guidelines.

Please let me know in case of any feedback.

2023-10-02 20:49 UTC, mezotv requested changes

2023-10-02 20:49 UTC, mezotv commented on Contributing.md
> +We are all eager to work on official website for the Would You Discord bot, and this document will help you to get started!
This line sounds a bit weird. Would be nice to change it to something more human like. deepl.com/write can help!

2023-10-02 20:51 UTC, pbelokon commented on Contributing.md
> +We are all eager to work on official website for the Would You Discord bot, and this document will help you to get started!
sure will do so

2023-10-02 20:59 UTC, pbelokon commented on Contributing.md
> +We are all eager to work on official website for the Would You Discord bot, and this document will help you to get started!
@mezotv  I have something in mind how does this sound: 

Thank you for showing an interest in contributing! All kinds of contributions are valuable to us. In this guide, we will help you to get started!

2023-10-02 21:09 UTC, mezotv commented on Contributing.md
> +We are all eager to work on official website for the Would You Discord bot, and this document will help you to get started!
Maybe like this "Thank you for your interest in contributing! All types of contributions are valuable to us. This guide will help you get started!"

2023-10-02 21:56 UTC, pbelokon commented on Contributing.md
> +We are all eager to work on official website for the Would You Discord bot, and this document will help you to get started!
Changed with the new commit

2023-10-02 21:57 UTC, mezotv commented
I will take a look tomorrow. Thanks!

2023-10-03 00:35 UTC, Podskio approved these changes

2023-10-03 04:34 UTC, mezotv approved these changes
Looks good!

2023-10-03 04:35 UTC, merged